#!/bin/sh -e

export PREFIX="poetry run "
export SOURCE_FILES="src"

set -x

${PREFIX}autoflake --in-place --recursive --ignore-init-module-imports --remove-all-unused-imports $SOURCE_FILES
${PREFIX}isort $SOURCE_FILES
${PREFIX}black $SOURCE_FILES
