#!/bin/sh -e

export PREFIX="poetry run "
export SOURCE_FILES="src"

set -x

${PREFIX}isort --check --diff $SOURCE_FILES
${PREFIX}black --check --diff $SOURCE_FILES
${PREFIX}pylint $SOURCE_FILES
${PREFIX}mypy $SOURCE_FILES
